/**
 * Joi validation schema for the `project` JSONB column in bng.projects.
 *
 * Generated by /reflect-schema from a sample row. Update by re-running the
 * skill after schema changes, or edit manually as requirements become clearer.
 *
 * The `.description()` on every key is the source of prose for the generated
 * data dictionary (`npm run data-dictionary` → data-dictionary/data-dictionary.md) and for
 * the Swagger UI. Keep them accurate: they document what is actually persisted.
 */
import Joi from 'joi'

import {
  habitatSizesSummarySchema,
  baselineUnitsTotalsSchema,
  redLineSchema,
  featureDataEnvelopeFields
} from './project-shared-schemas.js'
import { postInterventionDataSchema } from './project-post-intervention-schema.js'

const DISTINCTIVENESS_SCORE_DESCRIPTION =
  'Numeric distinctiveness score for the band, from bng-metric-engine.'

// Survey / provenance / planning metadata columns shared by the Habitats,
// Hedgerows and Rivers layers. Promoted to named fields by BMD-498. Returned as
// a fresh object each call because Joi schema objects are stateful and must not
// be shared between parent schemas.
const metadataSchemaKeys = () => ({
  siteName: Joi.string()
    .allow(null, '')
    .description('Site name from the GeoPackage (Site Name column).'),
  surveyDate: Joi.string()
    .allow(null, '')
    .description(
      'Survey date from the GeoPackage (Survey Date column), as stored in the source file.'
    ),
  surveyDetails: Joi.string()
    .allow(null, '')
    .description('Free-text survey details from the GeoPackage.'),
  comment: Joi.string()
    .allow(null, '')
    .description(
      'Free-text comment from the GeoPackage (Comment / Comments column).'
    ),
  mappedBy: Joi.string()
    .allow(null, '')
    .description('Name of the surveyor who mapped the feature (Mapped by).'),
  company: Joi.string()
    .allow(null, '')
    .description('Company responsible for the survey (Company column).'),
  baseMap: Joi.string()
    .allow(null, '')
    .description('Base map used during mapping (Base Map column).'),
  location: Joi.string()
    .allow(null, '')
    .description('Free-text location description from the GeoPackage.'),
  spatialRiskCategory: Joi.string()
    .allow(null, '')
    .description('Spatial risk category from the GeoPackage.'),
  habitatCreatedInAdvanceYears: Joi.string()
    .allow(null, '')
    .description(
      'Years the habitat was created in advance, from the GeoPackage (Habitat created in advance/years).'
    ),
  delayInStartingHabitatCreationYears: Joi.string()
    .allow(null, '')
    .description(
      'Years of delay before starting habitat creation, from the GeoPackage (Delay in starting habitat creation/years).'
    ),
  rawDistinctiveness: Joi.string()
    .allow(null, '')
    .description(
      'Raw distinctiveness value as written in the GeoPackage — the Baseline Distinctiveness column for the baseline document, the Proposed Distinctiveness column for the post-intervention document. Informational only; the authoritative distinctiveness band is the `distinctiveness` field resolved by bng-metric-engine.'
    )
})

const STRATEGIC_SIGNIFICANCE_DESCRIPTION =
  'Strategic significance category from the GeoPackage.'

const RETENTION_CATEGORY_DESCRIPTION = 'Retention category from the GeoPackage.'

const siteSchema = Joi.object({
  name: Joi.string().description('Free-text name of the development site.'),
  grid_ref: Joi.string().description(
    'Ordnance Survey national grid reference for the site.'
  )
}).description('Development site details.')

const unitsSchema = Joi.object({
  habitat: Joi.number().description(
    'Project-level area-habitat biodiversity unit total.'
  ),
  hedgerow: Joi.number().description(
    'Project-level hedgerow biodiversity unit total.'
  ),
  watercourse: Joi.number().description(
    'Project-level watercourse biodiversity unit total.'
  )
}).description('Project-level biodiversity unit summary.')

const habitatSchema = Joi.object({
  featureId: Joi.string()
    .uuid()
    .required()
    .description(
      'UUID assigned on import; join key to the bng.baseline_habitats geometry row.'
    ),
  ref: Joi.string()
    .allow(null, '')
    .description('Parcel reference from the GeoPackage (Parcel Ref column).'),
  type: Joi.string()
    .allow(null, '')
    .description("Baseline habitat type, e.g. 'Lowland meadows'."),
  broadType: Joi.string()
    .allow(null, '')
    .description("Baseline broad habitat type, e.g. 'Grassland'."),
  distinctiveness: Joi.string()
    .allow(null, '')
    .description(
      "Distinctiveness band resolved by bng-metric-engine from the habitat type, e.g. 'High'. Set once the habitat type is recognised."
    ),
  distinctivenessScore: Joi.number()
    .allow(null)
    .description(DISTINCTIVENESS_SCORE_DESCRIPTION),
  condition: Joi.string()
    .allow(null, '')
    .description("Baseline condition assessment, e.g. 'Good'."),
  conditionScore: Joi.number()
    .allow(null)
    .description(
      'Numeric condition score from bng-metric-engine. Set during import enrichment and on habitat edits.'
    ),
  strategicSignificance: Joi.string()
    .allow(null, '')
    .description(STRATEGIC_SIGNIFICANCE_DESCRIPTION),
  retentionCategory: Joi.string()
    .allow(null, '')
    .description(RETENTION_CATEGORY_DESCRIPTION),
  area: Joi.number()
    .allow(null)
    .description(
      'Parcel area in square metres, measured in PostGIS and rounded to the nearest integer. This is the value fed to the unit calculation.'
    ),
  sizeSquareMetres: Joi.number()
    .allow(null)
    .description('Exact parcel area in square metres as measured in PostGIS.'),
  status: Joi.string()
    .valid('Complete', 'Incomplete')
    .required()
    .description(
      "'Complete' when broad type, habitat type and condition are all set; otherwise 'Incomplete'."
    ),
  units: Joi.number()
    .allow(null)
    .description(
      'Baseline biodiversity units for the parcel. Written by both the import/enrichment path and the habitat-edit endpoint; read by the frontend display and the baseline unit totals.'
    ),
  ...metadataSchemaKeys(),
  properties: Joi.object()
    .unknown(true)
    .description(
      'Raw attribute columns copied verbatim from the GeoPackage Habitats layer.'
    )
}).description('An area (polygon) habitat parcel.')

// An individual tree (Urban Trees layer). Treated as a special area habitat, so
// it reuses habitatSchema's derived block (distinctiveness, condition scores,
// units, status, metadata) verbatim — only the parcel-specific descriptions are
// overridden and the tree-specific source columns appended. Deriving from
// habitatSchema avoids duplicating the shared field definitions.
const treeSchema = habitatSchema
  .append({
    featureId: Joi.string()
      .uuid()
      .required()
      .description(
        'UUID assigned on import; join key to the bng.baseline_trees geometry row.'
      ),
    ref: Joi.string()
      .allow(null, '')
      .description('Tree reference from the GeoPackage (Tree Ref column).'),
    type: Joi.string()
      .allow(null, '')
      .description(
        "Tree habitat type — 'Urban tree' or 'Rural tree', derived from the Rural or Urban Tree column."
      ),
    broadType: Joi.string()
      .allow(null, '')
      .description("Always 'Individual trees' for tree features."),
    distinctiveness: Joi.string()
      .allow(null, '')
      .description(
        'Distinctiveness band resolved by bng-metric-engine from the tree habitat type. Trees are Medium distinctiveness.'
      ),
    area: Joi.number()
      .allow(null)
      .description(
        'Notional tree area in square metres (per-size reference value), rounded. This is the value fed to the unit calculation.'
      ),
    sizeSquareMetres: Joi.number()
      .allow(null)
      .description('Notional tree area in square metres (per-size reference).'),
    units: Joi.number()
      .allow(null)
      .description(
        'Baseline biodiversity units for the tree, from bng-metric-engine using the area-habitat calculation.'
      ),
    properties: Joi.object()
      .unknown(true)
      .description(
        'Raw attribute columns copied verbatim from the GeoPackage Urban Trees layer.'
      ),
    // Tree-specific source columns not present on parcels.
    treeSize: Joi.string()
      .allow(null, '')
      .description(
        "Tree size band from the GeoPackage (Baseline/Proposed Tree Size), e.g. 'Medium'. Determines the per-tree area."
      ),
    treeSpecies: Joi.string()
      .allow(null, '')
      .description(
        'Tree species/type free text from the GeoPackage (Baseline/Proposed Tree Type column).'
      ),
    ruralOrUrban: Joi.string()
      .allow(null, '')
      .description(
        'Raw Rural or Urban Tree value as written in the GeoPackage (e.g. "Urban").'
      ),
    count: Joi.number()
      .allow(null)
      .description(
        'Count column from the GeoPackage. Recorded for reference; each tree is treated as a single tree (one row) for area and units.'
      )
  })
  .description('An individual tree feature (point).')

// Hedgerows and watercourses share the same linear-feature shape. This factory
// keeps their field order and prose identical while letting each supply its own
// descriptions and module-specific fields. Field order is significant — it
// drives the generated data dictionary — so `afterCondition` and
// `beforeProperties` splice extra keys into the exact positions each module
// uses.
function linearFeatureSchema({
  geometryRow,
  typeDescription,
  conditionDescription,
  afterCondition = {},
  distinctivenessDescription,
  statusDescription,
  unitsDescription,
  beforeProperties = {},
  propertiesDescription,
  rootDescription
}) {
  return Joi.object({
    featureId: Joi.string()
      .uuid()
      .required()
      .description(
        `UUID assigned on import; join key to the ${geometryRow} geometry row.`
      ),
    ref: Joi.string()
      .allow(null, '')
      .description(
        'Feature reference from the GeoPackage (Parcel Ref column).'
      ),
    type: Joi.string().allow(null, '').description(typeDescription),
    condition: Joi.string().allow(null, '').description(conditionDescription),
    ...afterCondition,
    distinctiveness: Joi.string()
      .allow(null, '')
      .description(distinctivenessDescription),
    distinctivenessScore: Joi.number()
      .allow(null)
      .description(DISTINCTIVENESS_SCORE_DESCRIPTION),
    conditionScore: Joi.number()
      .allow(null)
      .description('Numeric condition score from bng-metric-engine.'),
    length: Joi.number()
      .allow(null)
      .description(
        'Length in metres (PostGIS size, rounded). Set during unit enrichment.'
      ),
    sizeMetres: Joi.number()
      .allow(null)
      .description('Length in metres as measured in PostGIS.'),
    status: Joi.string()
      .valid('Complete', 'Incomplete')
      .required()
      .description(statusDescription),
    units: Joi.number().allow(null).description(unitsDescription),
    strategicSignificance: Joi.string()
      .allow(null, '')
      .description(STRATEGIC_SIGNIFICANCE_DESCRIPTION),
    retentionCategory: Joi.string()
      .allow(null, '')
      .description(RETENTION_CATEGORY_DESCRIPTION),
    ...metadataSchemaKeys(),
    ...beforeProperties,
    properties: Joi.object().unknown(true).description(propertiesDescription)
  }).description(rootDescription)
}

const linearHabitatSchema = linearFeatureSchema({
  geometryRow: 'bng.baseline_hedgerows',
  typeDescription: 'Hedgerow type (Baseline Hedge Type column).',
  conditionDescription: 'Hedgerow condition assessment.',
  distinctivenessDescription:
    'Distinctiveness band resolved by bng-metric-engine from the hedgerow type.',
  statusDescription:
    "'Complete' when type and condition are both set; otherwise 'Incomplete'.",
  unitsDescription:
    'Baseline biodiversity units for the hedgerow, from bng-metric-engine (BMD-427/428).',
  propertiesDescription:
    'Raw attribute columns copied verbatim from the GeoPackage Hedgerows layer.',
  rootDescription: 'A hedgerow (linear) feature.'
})

const watercourseHabitatSchema = linearFeatureSchema({
  geometryRow: 'bng.baseline_watercourses',
  typeDescription: 'Watercourse type (Baseline River Type column).',
  conditionDescription: 'Watercourse condition assessment.',
  afterCondition: {
    riparianEncroachment: Joi.string()
      .allow(null, '')
      .description('Riparian-zone encroachment category from the GeoPackage.'),
    watercourseEncroachment: Joi.string()
      .allow(null, '')
      .description('Watercourse encroachment category from the GeoPackage.')
  },
  distinctivenessDescription:
    'Distinctiveness band resolved by bng-metric-engine from the watercourse type.',
  statusDescription:
    "'Complete' when type, condition, riparian encroachment and watercourse encroachment are all set; otherwise 'Incomplete'.",
  unitsDescription:
    'Baseline biodiversity units for the watercourse, from bng-metric-engine (BMD-427/428).',
  beforeProperties: {
    enhancementType: Joi.string()
      .allow(null, '')
      .description('Enhancement type from the GeoPackage Rivers layer.'),
    waterEncroachmentMultiplier: Joi.number()
      .allow(null)
      .description(
        'Watercourse-encroachment multiplier applied by bng-metric-engine when computing units.'
      ),
    riparianEncroachmentMultiplier: Joi.number()
      .allow(null)
      .description(
        'Riparian-encroachment multiplier applied by bng-metric-engine when computing units.'
      )
  },
  propertiesDescription:
    'Raw attribute columns copied verbatim from the GeoPackage Watercourses layer.',
  rootDescription: 'A watercourse (linear) feature.'
})

const projectDetailsSchema = Joi.object({
  localPlanningAuthority: Joi.string()
    .allow(null, '')
    .description('Local Planning Authority name.'),
  surveyCompleters: Joi.string()
    .allow(null, '')
    .description('Names of survey completer(s).'),
  surveyCompletionDate: Joi.string()
    .allow(null, '')
    .description('Survey completion date in DD/MM/YYYY format.'),
  developmentType: Joi.string()
    .valid('Small site', 'Large site')
    .allow(null)
    .description('Development type classification.'),
  nsips: Joi.string()
    .valid('Yes', 'No')
    .allow(null)
    .description(
      'Whether the project is a National Significant Infrastructure Project.'
    ),
  surveyCompletedBy: Joi.string()
    .allow(null, '')
    .description('Name of the person who completed the survey.'),
  dateOfSurvey: Joi.string()
    .allow(null, '')
    .description('Date of survey in DD/MM/YYYY format.'),
  applicant: Joi.string().allow(null, '').description('Applicant name.')
})
  .allow(null)
  .description('Project details entered by the user.')

const habitatDataSchema = Joi.object({
  ...featureDataEnvelopeFields,
  redLine: redLineSchema,
  habitats: Joi.array()
    .items(habitatSchema)
    .description('Area (polygon) habitat parcels in the baseline.'),
  trees: Joi.array()
    .items(treeSchema)
    .description('Individual tree (point) features in the baseline.'),
  hedgerows: Joi.array()
    .items(linearHabitatSchema)
    .description('Hedgerow (linear) features in the baseline.'),
  watercourses: Joi.array()
    .items(watercourseHabitatSchema)
    .description('Watercourse (linear) features in the baseline.'),
  habitatSizes: habitatSizesSummarySchema,
  units: baselineUnitsTotalsSchema
}).description(
  'Imported baseline state: features, sizes and unit totals. Written by the baseline upload flow.'
)

const projectSchema = Joi.object({
  name: Joi.string().description(
    'Project name shown to the user; editable via PATCH /projects/{id}.'
  ),
  site: siteSchema,
  units: unitsSchema,
  details: projectDetailsSchema,
  baseline: habitatDataSchema,
  postIntervention: postInterventionDataSchema
}).description(
  'Root document stored in the bng.projects.project JSONB column (and snapshotted into bng.audit_log.project).'
)

export {
  projectSchema,
  projectDetailsSchema,
  siteSchema,
  unitsSchema,
  baselineUnitsTotalsSchema,
  habitatDataSchema,
  habitatSchema,
  treeSchema,
  linearHabitatSchema,
  watercourseHabitatSchema,
  postInterventionDataSchema
}
