/**
 * Joi validation schema for the `project` JSONB column in bng.projects.
 *
 * Generated by /reflect-schema from a sample row. Update by re-running the
 * skill after schema changes, or edit manually as requirements become clearer.
 */
import Joi from 'joi'

import { MAX_FILE_SIZE_BYTES } from '../services/s3/download-file.js'

const MAX_FILENAME_LENGTH = 255

// Whitelist-only approach addresses six classes of attack in one rule:
//   1. Extension spoofing  — bidi overrides (U+202E etc.) not in [a-zA-Z0-9 ._-]
//   2. Path traversal      — / and leading dots excluded; .. sequences impossible
//   3. Log injection       — \n, \r and other control chars not in the set
//   4. Wrong extension     — \.gpkg$ is mandatory (case-insensitive)
//   5. Invisible chars     — zero-width / formatting codepoints not in the set
//   6. SQL injection       — ' " ; not in the set; lone - cannot form --
const SAFE_FILENAME_RE = /^[a-z0-9][a-z0-9 ._-]*\.gpkg$/i

const siteSchema = Joi.object({
  name: Joi.string(),
  grid_ref: Joi.string()
})

const unitsSchema = Joi.object({
  habitat: Joi.number(),
  hedgerow: Joi.number(),
  watercourse: Joi.number()
})

const habitatSizesSummarySchema = Joi.object({
  areaHabitats: Joi.object({
    totalSquareMetres: Joi.number().required()
  }).required(),
  hedgerows: Joi.object({
    totalMetres: Joi.number().required()
  }).required(),
  watercourses: Joi.object({
    totalMetres: Joi.number().required()
  }).required()
}).allow(null)

const baselineUnitsTotalsSchema = Joi.object({
  totalUnits: Joi.number().required(),
  habitatsTotal: Joi.number().required(),
  hedgerowsTotal: Joi.number().required(),
  watercoursesTotal: Joi.number().required()
})

const redLineSchema = Joi.object({
  featureId: Joi.string().uuid().required(),
  properties: Joi.object().unknown(true)
}).allow(null)

const habitatSchema = Joi.object({
  featureId: Joi.string().uuid().required(),
  ref: Joi.string().allow(null, ''),
  type: Joi.string().allow(null, ''),
  broadType: Joi.string().allow(null, ''),
  distinctiveness: Joi.string().allow(null, ''),
  distinctivenessScore: Joi.number().allow(null),
  condition: Joi.string().allow(null, ''),
  strategicSignificance: Joi.string().allow(null, ''),
  retentionCategory: Joi.string().allow(null, ''),
  area: Joi.number().allow(null),
  sizeSquareMetres: Joi.number().allow(null),
  status: Joi.string().valid('Complete', 'Incomplete').required(),
  units: Joi.number().allow(null),
  properties: Joi.object().unknown(true)
})

const linearHabitatSchema = Joi.object({
  featureId: Joi.string().uuid().required(),
  ref: Joi.string().allow(null, ''),
  type: Joi.string().allow(null, ''),
  condition: Joi.string().allow(null, ''),
  length: Joi.number().allow(null),
  sizeMetres: Joi.number().allow(null),
  status: Joi.string().valid('Complete', 'Incomplete').required(),
  properties: Joi.object().unknown(true)
})

const watercourseHabitatSchema = Joi.object({
  featureId: Joi.string().uuid().required(),
  ref: Joi.string().allow(null, ''),
  type: Joi.string().allow(null, ''),
  condition: Joi.string().allow(null, ''),
  riparianEncroachment: Joi.string().allow(null, ''),
  watercourseEncroachment: Joi.string().allow(null, ''),
  length: Joi.number().allow(null),
  sizeMetres: Joi.number().allow(null),
  status: Joi.string().valid('Complete', 'Incomplete').required(),
  properties: Joi.object().unknown(true)
})

const baselineSchema = Joi.object({
  uploadId: Joi.string().uuid().allow(null),
  filename: Joi.string()
    .max(MAX_FILENAME_LENGTH)
    .pattern(SAFE_FILENAME_RE)
    .allow(null),
  fileSize: Joi.number().integer().min(0).max(MAX_FILE_SIZE_BYTES).allow(null),
  importedAt: Joi.string().isoDate(),
  redLine: redLineSchema,
  habitats: Joi.array().items(habitatSchema),
  hedgerows: Joi.array().items(linearHabitatSchema),
  watercourses: Joi.array().items(watercourseHabitatSchema),
  habitatSizes: habitatSizesSummarySchema,
  units: baselineUnitsTotalsSchema
})

const projectSchema = Joi.object({
  name: Joi.string(),
  site: siteSchema,
  units: unitsSchema,
  baseline: baselineSchema
})

export {
  projectSchema,
  siteSchema,
  unitsSchema,
  baselineUnitsTotalsSchema,
  baselineSchema,
  habitatSchema,
  linearHabitatSchema,
  watercourseHabitatSchema
}
