export const ERROR_CODES = {
  GPKG_INVALID_FILE: 'GPKG_INVALID_FILE',
  GPKG_NOT_A_GEOPACKAGE: 'GPKG_NOT_A_GEOPACKAGE',
  GPKG_MISSING_SYSTEM_TABLE: 'GPKG_MISSING_SYSTEM_TABLE',
  GPKG_MISSING_LAYER: 'GPKG_MISSING_LAYER',
  GPKG_RLB_NO_GEOMETRY_COLUMN: 'GPKG_RLB_NO_GEOMETRY_COLUMN',
  GPKG_RLB_INVALID_GEOMETRY_COLUMN_NAME:
    'GPKG_RLB_INVALID_GEOMETRY_COLUMN_NAME',
  GPKG_RLB_UNREADABLE_GEOMETRY: 'GPKG_RLB_UNREADABLE_GEOMETRY',
  GPKG_RLB_NO_POLYGON: 'GPKG_RLB_NO_POLYGON',
  GPKG_RLB_TOO_MANY_POLYGONS: 'GPKG_RLB_TOO_MANY_POLYGONS',
  REDLINE_OUTSIDE_ENGLAND: 'REDLINE_OUTSIDE_ENGLAND',
  REDLINE_AREA_TOO_LARGE: 'REDLINE_AREA_TOO_LARGE',
  NO_HABITAT_AREAS: 'NO_HABITAT_AREAS',
  REDLINE_INVALID_GEOMETRY: 'REDLINE_INVALID_GEOMETRY',
  AREA_PARCELS_INVALID_GEOMETRY: 'AREA_PARCELS_INVALID_GEOMETRY',
  PARCEL_OVERLAPS: 'PARCEL_OVERLAPS',
  SLIVERS_OUTSIDE_REDLINE: 'SLIVERS_OUTSIDE_REDLINE',
  AREA_PARCELS_OUTSIDE_REDLINE: 'AREA_PARCELS_OUTSIDE_REDLINE',
  HEDGEROWS_OUTSIDE_REDLINE: 'HEDGEROWS_OUTSIDE_REDLINE',
  WATERCOURSES_OUTSIDE_REDLINE: 'WATERCOURSES_OUTSIDE_REDLINE',
  IGGIS_OUTSIDE_REDLINE: 'IGGIS_OUTSIDE_REDLINE',
  TREES_OUTSIDE_REDLINE: 'TREES_OUTSIDE_REDLINE',
  AREA_SUM_MISMATCH: 'AREA_SUM_MISMATCH'
}

export function makeError(code, message, offendingFeatures = []) {
  return { code, message, offendingFeatures }
}

/**
 * Build a stable identifier for a feature so the dropout page can list which
 * polygons failed. Prefers `fid`, then a `name`-like property, else falls
 * back to the array index.
 */
export function featureRef(feature, index) {
  const props = feature.properties ?? {}
  const id = props.fid ?? props.id ?? props.OBJECTID ?? index
  const name = props.name ?? props.Name ?? props.NAME ?? null
  return name ? { id, name } : { id }
}
