export const ERROR_CODES = Object.freeze({
  GPKG_INVALID_FILE: 'GPKG_INVALID_FILE',
  GPKG_NOT_A_GEOPACKAGE: 'GPKG_NOT_A_GEOPACKAGE',
  GPKG_MISSING_SYSTEM_TABLE: 'GPKG_MISSING_SYSTEM_TABLE',
  GPKG_MISSING_LAYER: 'GPKG_MISSING_LAYER',
  GPKG_RLB_NO_GEOMETRY_COLUMN: 'GPKG_RLB_NO_GEOMETRY_COLUMN',
  GPKG_RLB_INVALID_GEOMETRY_COLUMN_NAME:
    'GPKG_RLB_INVALID_GEOMETRY_COLUMN_NAME',
  GPKG_RLB_UNREADABLE_GEOMETRY: 'GPKG_RLB_UNREADABLE_GEOMETRY',
  GPKG_RLB_NO_POLYGON: 'GPKG_RLB_NO_POLYGON',
  GPKG_RLB_TOO_MANY_POLYGONS: 'GPKG_RLB_TOO_MANY_POLYGONS',
  GPKG_UNEXPECTED_FEATURE_LAYER: 'GPKG_UNEXPECTED_FEATURE_LAYER',
  GPKG_BASELINE_CONTENTS_DATA_TYPE: 'GPKG_BASELINE_CONTENTS_DATA_TYPE',
  GPKG_BASELINE_SRS_ID: 'GPKG_BASELINE_SRS_ID',
  GPKG_BASELINE_GPKG_SRS_INCONSISTENT: 'GPKG_BASELINE_GPKG_SRS_INCONSISTENT',
  GPKG_BASELINE_GEOMETRY_COLUMN_NAME: 'GPKG_BASELINE_GEOMETRY_COLUMN_NAME',
  GPKG_BASELINE_GEOMETRY_TYPE_NAME: 'GPKG_BASELINE_GEOMETRY_TYPE_NAME',
  GPKG_BASELINE_MISSING_COLUMN: 'GPKG_BASELINE_MISSING_COLUMN',
  GPKG_BASELINE_COLUMN_SQLITE_TYPE: 'GPKG_BASELINE_COLUMN_SQLITE_TYPE',
  GPKG_BASELINE_COLUMN_NOT_NULL: 'GPKG_BASELINE_COLUMN_NOT_NULL',
  GPKG_BASELINE_COLUMN_PRIMARY_KEY: 'GPKG_BASELINE_COLUMN_PRIMARY_KEY',
  GPKG_BASELINE_GEOMETRY_REGISTRATION_MISSING:
    'GPKG_BASELINE_GEOMETRY_REGISTRATION_MISSING',
  NO_REDLINE: 'NO_REDLINE',
  GPKG_HABITATS_NO_GEOMETRY_COLUMN: 'GPKG_HABITATS_NO_GEOMETRY_COLUMN',
  GPKG_HABITATS_INVALID_GEOMETRY_COLUMN_NAME:
    'GPKG_HABITATS_INVALID_GEOMETRY_COLUMN_NAME',
  GPKG_HABITATS_UNREADABLE_GEOMETRY: 'GPKG_HABITATS_UNREADABLE_GEOMETRY',
  REDLINE_OUTSIDE_ENGLAND: 'REDLINE_OUTSIDE_ENGLAND',
  REDLINE_AREA_TOO_LARGE: 'REDLINE_AREA_TOO_LARGE',
  NO_HABITAT_AREAS: 'NO_HABITAT_AREAS',
  REDLINE_INVALID_GEOMETRY: 'REDLINE_INVALID_GEOMETRY',
  AREA_PARCELS_INVALID_GEOMETRY: 'AREA_PARCELS_INVALID_GEOMETRY',
  PARCEL_OVERLAPS: 'PARCEL_OVERLAPS',
  SLIVERS_INSIDE_REDLINE: 'SLIVERS_INSIDE_REDLINE',
  SLIVERS_OUTSIDE_REDLINE: 'SLIVERS_OUTSIDE_REDLINE',
  AREA_PARCELS_OUTSIDE_REDLINE: 'AREA_PARCELS_OUTSIDE_REDLINE',
  HEDGEROWS_OUTSIDE_REDLINE: 'HEDGEROWS_OUTSIDE_REDLINE',
  WATERCOURSES_OUTSIDE_REDLINE: 'WATERCOURSES_OUTSIDE_REDLINE',
  IGGIS_OUTSIDE_REDLINE: 'IGGIS_OUTSIDE_REDLINE',
  TREES_OUTSIDE_REDLINE: 'TREES_OUTSIDE_REDLINE',
  AREA_SUM_MISMATCH: 'AREA_SUM_MISMATCH',
  HABITAT_DISTINCTIVENESS_NOT_IN_SCOPE: 'HABITAT_DISTINCTIVENESS_NOT_IN_SCOPE',
  DUPLICATE_HABITAT_REF: 'DUPLICATE_HABITAT_REF',

  /** PostGIS query to calculate habitat sizes failed (e.g. temporary DB connection problem). */
  SIZING_FAILED: 'SIZING_FAILED',

  /** Extracted document fails baselineSchema — e.g. filename or fileSize from CDP Uploader exceeds allowed bounds. */
  INVALID_FILE_METADATA: 'INVALID_FILE_METADATA',

  /** Non-GeoPackage failure while running the baseline validation pipeline (e.g. unexpected exception). */
  VALIDATION_FAILED: 'VALIDATION_FAILED'
})

export function makeError(code, message, details) {
  return details === undefined ? { code, message } : { code, message, details }
}
