name: Check DB Schema

on:
  pull_request:

env:
  LIQUIBASE_VERSION: '5.0.1'

  POSTGRES_USER: liquibase
  POSTGRES_PASSWORD: liquibase
  POSTGRES_DB: liquibase

jobs:
  liquibase-update:
    name: Validate and Apply DB Schema
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: liquibase
          POSTGRES_PASSWORD: liquibase
          POSTGRES_DB: liquibase
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U liquibase"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Liquibase
        run: |
          mkdir -p ./liquibase
          curl -sL "https://github.com/liquibase/liquibase/releases/download/v${LIQUIBASE_VERSION}/liquibase-${LIQUIBASE_VERSION}.tar.gz" | tar xz -C ./liquibase
          ./liquibase/liquibase lpm add postgresql --global

      - name: Validate Liquibase changelog
        run: |
          ./liquibase/liquibase \
            --changelog-file=changelog/db.changelog.xml \
            --url=jdbc:postgresql://localhost:5432/${POSTGRES_DB} \
            --username=${POSTGRES_USER} \
            --password=${POSTGRES_PASSWORD} \
            validate

      - name: Run Liquibase update
        run: |
          ./liquibase/liquibase \
            --changelog-file=changelog/db.changelog.xml \
            --url=jdbc:postgresql://localhost:5432/${POSTGRES_DB} \
            --username=${POSTGRES_USER} \
            --password=${POSTGRES_PASSWORD} \
            update
